esphome:
    name: greenhouse
    friendly_name: "Теплица"
    area: "Теплица"

esp32:
    board: esp32dev
    framework:
        type: esp-idf

# Enable Home Assistant API
api:
    encryption:
        key: !secret greenhouse_api_encryption_key

ota:
    -   platform: esphome
        password: !secret greenhouse_ota_password

packages:
    common: !include
        file: common/common-settings.yaml

    tks1: !include
        file: common/tks-m8.yaml
        vars:
            tks_name: tks1
            tks_action_time: tks1_action_time
            tks_k1: GPIO27
            tks_k2: GPIO14
            tks_sw1: GPIO25
            tks_sw2: GPIO26
            tks_max_value: 10
    tks2: !include
        file: common/tks-m8.yaml
        vars:
            tks_name: tks2
            tks_action_time: tks2_action_time
            tks_k1: GPIO18
            tks_k2: GPIO19
            tks_sw1: GPIO22
            tks_sw2: GPIO23
            tks_max_value: 20
    light1_no_display: !include
        file: common/no-display.yaml
        vars:
            light_name: greenhouse
    light1_no_button: !include
        file: common/no-button.yaml
        vars:
            light_name: greenhouse
    light1: !include
        file: common/auto-light.yaml
        vars:
            light_name: greenhouse
            name_prefix: "Greenhouse"
            motion_gpio: GPIO33
            motion_pullup: true
            relay_gpio: GPIO17
            relay_inverted: true
            timeout_max_value: 300

one_wire:
    -   platform: gpio
        pin: GPIO4

sensor:
    -   platform: dht
        pin: GPIO5
        model: AM2302
        temperature:
            name: "Greenhouse Temperature"
            id: inner_temp
        humidity:
            name: "Greenhouse Humidity"
        update_interval: 30s
    -   platform: dallas_temp
        name: "Ground Temperature"
        update_interval: 60s
#    -   platform: adc
#        pin: GPIO32
#    -   platform: adc
#        pin: GPIO34
#    -   platform: adc
#        pin: GPIO35

output:
    -   platform: template
        id: pid_tks_control
        type: float
        write_action:
            -   if:
                    condition:
                        lambda: return id(window_pid).mode != CLIMATE_MODE_OFF;
                    then:
                        -   number.set:
                                id: tks1_action_time
                                value: !lambda 'return int(ceil(state * 10 / 10 * 10));' # from tks1 tks_max_value
                        -   number.set:
                                id: tks2_action_time
                                value: !lambda 'return int(ceil(state * 20 / 10 * 10));' # from tks2 tks_max_value

    -   platform: template
        id: pid_relay_control
        type: float
        write_action:
            -   lambda: |-
                    if (id(heater_pid).mode != CLIMATE_MODE_OFF) {
                        if (state > 0.1) {
                            id(heater_1).turn_on();
                        } else {
                            id(heater_1).turn_off();
                        }
                        if (state > 0.8) {
                            id(heater_2).turn_on();
                        } else {
                            id(heater_2).turn_off();
                        }
                    } else {
                        id(heater_1).turn_off();
                        id(heater_2).turn_off();
                    }

switch:
    -   platform: gpio
        pin: GPIO15
        id: heater_1
        name: "Heater 1"
        inverted: true
        restore_mode: ALWAYS_OFF
    -   platform: gpio
        pin: GPIO21
        id: heater_2
        name: "Heater 2"
        inverted: true
        restore_mode: ALWAYS_OFF
    -   platform: gpio
        pin: GPIO16
        id: external_socket
        name: "External socket"
        inverted: true
        restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
    -   platform: gpio
        pin:
            number: GPIO13
            mode:
                input: true
                pullup: true
        device_class: door
        name: "Greenhouse door"
        id: door_1
        filters:
            -   delayed_on: 50ms
            -   delayed_off: 50ms

climate:
    -   platform: pid
        id: window_pid
        name: "Window"
        sensor: inner_temp
        default_target_temperature: 28°C
        cool_output: pid_tks_control
        deadband_parameters:
            threshold_high: 0.4°C
            threshold_low: 0.4°C
        control_parameters:
            kp: 0.02
            ki: 0.8
            kd: 0.5
            min_integral: -0.6
            max_integral: 0.6
            output_averaging_samples: 32
            derivative_averaging_samples: 16
        visual:
            min_temperature: 20
            max_temperature: 38
            temperature_step:
                target_temperature: 1
                current_temperature: 0.1

    -   platform: pid
        id: heater_pid
        name: "Heater"
        sensor: inner_temp
        default_target_temperature: 8°C
        heat_output: pid_relay_control
        deadband_parameters:
            threshold_high: 0.2°C
            threshold_low: 0.2°C
        control_parameters:
            kp: 0.05
            ki: 0.1
            kd: 0.2
            output_averaging_samples: 4
            derivative_averaging_samples: 8
        visual:
            min_temperature: -10
            max_temperature: 10
            temperature_step:
                target_temperature: 1
                current_temperature: 0.1

